service: "binary-api-typescript"

plugins:
  - serverless-webpack
  - "@kalarrs/serverless-project-utils"
  - "@kalarrs/serverless-shared-api-gateway"

provider:
  name: aws
  runtime: nodejs8.10
  profile: ${file(../serverless.yml):provider.profile}
  region: ${file(../serverless.yml):provider.region}
  stage: ${file(../serverless.yml):provider.stage}
  timeout: 10
  memorySize: 128
  apiGatewayRestApiName: ${file(../serverless.yml):provider.apiGatewayRestApiName}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "polly:SynthesizeSpeech"
      Resource: "*"

functions:
  postSpeech:
    handler: src/handler.postSpeech
    events:
      - http:
          method: get
          path: typescript/speech
          cors: true

custom:
  user: ${file(../serverless.yml):custom.user}
  localDevPort: 5000
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: true
