provider:
  environment:
    CHANGE_VALUE: "foo"
    MONGODB_URI: "mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]"

custom:
  apiGateway:
    name: "change"
    description: "Development API for change.com"
    customDomain:
      name: "dev.change.com"
      # certificateName: "*.change.com"
      certificateArn: arn:aws:acm:us-east-1:::certificate/12345
      basePathMapping: ""
