service: "basic-crud"

plugins:
  - serverless-webpack
  - "@kalarrs/serverless-local-dev-server"
  - "@kalarrs/serverless-shared-api-gateway"

provider:
  name: aws
  runtime: nodejs6.10
  profile: ${file(../serverless.yml):provider.profile}
  region: ${file(../serverless.yml):provider.region}
  stage: ${file(../serverless.yml):provider.stage}
  apiGatewayRestApiName: ${file(../serverless.yml):provider.apiGatewayRestApiName}

  environment:
    CHANGE_VALUE: ${env:CHANGE_VALUE, file(../serverless.yml):provider.environment.CHANGE_VALUE}

functions:
  # list
  getChanges:
    handler: src/handler.getChanges
    events:
      - http:
          method: get
          path: changes
          cors: true
  # create
  postChanges:
    handler: src/handler.postChanges
    events:
      - http:
          method: post
          path: changes
          cors: true
  # get
  getChange:
    handler: src/handler.getChange
    events:
      - http:
          method: get
          path: changes/{changeId}
          cors: true
  # delete
  deleteChange:
    handler: src/handler.deleteChange
    events:
      - http:
          method: delete
          path: changes/{changeId}
          cors: true
custom:
  user: ${file(../serverless.yml):custom.user}
  localDevPort: 5000
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: true
