service:
  name: ffmpeg-layer

provider:
  name: aws
  profile: ${file(../../serverless.yml):provider.profile}
  region: ${file(../../serverless.yml):provider.region}
  stage: ${file(../../serverless.yml):provider.stage}

layers:
  ffmpeg:
    name: ffmpeg-${self:provider.stage}
    path: src
